# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Construct the joint covariance matrix.
#'
#' The joint covariance matrix for the VAR(1) model is constructed by
#'   joining blocks based on lags.
#'
#' @param A Numeric VAR(1) coefficient matrix.
#' @param B Numeric covariance matrix for the observations, without
#'   observation errors.
#' @param D Numeric covariance matrix for the observation errors.
#' @param H Integer matrix giving the lags corresponding to each block.
#' @return Joint covariance matrix, including observation error variances.
cov_mat <- function(A, B, D, H) {
    .Call(`_IAMUQ_cov_mat`, A, B, D, H)
}

#' Run the IAM.
#'
#' @param yr Numeric vector of years for the model run.
#' @param P0 Double, the initial population.
#' @param psi Numeric vector with three components for the population
#'   dynamics variables psi1 (growth rate), psi2 (half-saturation constant),
#'   and psi3 (carrying capacity).
#' @param alpha Double, the rate of technological progress for total
#'   factor productivity.
#' @param A0 Double, the initial total factor productivity.
#' @param As Double, the total factor productivity saturation level.
#' @param s Double, the savings rate (must be less than 1).
#' @param lambda Double, the elasticity of production with respect to labor.
#' @param delta Double,the capital depreciation rate (must be less than 1).
#' @param pi Double, the labor force participation rate (must be less than 1
#'   ).
#' @param kappa Double, the rate of technological penetration (must be less
#'   than 1).
#' @param gamma Numeric matrix, each column is the penetration for the
#'   corresponding technology, and each row corresponds to a model year.
#' @param rho Numeric vector for the carbon intensities of each technology.
#' @param init Optional initial values for Q, and C.
#' @return Data frame of model output.
model_run <- function(yr, P0, psi, alpha, A0, As, s, lambda, delta, pi, kappa, gamma, rho, init) {
    .Call(`_IAMUQ_model_run`, yr, P0, psi, alpha, A0, As, s, lambda, delta, pi, kappa, gamma, rho, init)
}

